---
title: ""
author: ""
date: ""
output: html_document
params:
    day1:
        label: "Input dataset1:"
        value: "2024-02-05"
        input: date
    day2:
        label: "Input dataset2:"
        value: "2024-02-06"
        input: date
    event_start_time_day1: "09:30"
    event_end_time_day1: "13:00"
    event_start_time_day2: "09:30"
    event_end_time_day2: "13:00"
    session_joining_link: ""
    lead_instructor: "Neil Shephard"


---


<!--- Send this email around 1 week prior to event --->

We're looking forward to welcoming you to the RSE Sheffield training session on **git & GitHub through GitKraken Client - from Zero to Hero!**


### SETUP

Prior to attending, you need to **install the software we are going to use and create an account on GitHub. <span
style="color: #d1410c;">Please ensure you have completed setup before the course begins.</span>**

Instructions on how to create the account as well as install all the software required can be found on the [**Setup
chapter**](https://srse-git-github-zero2hero.netlify.app/setup/) of the course materials. If you have any problems with
your setup, please get in touch with us for assistance *before* the course begins. To ensure you have the advantages of
a [GitHub Educational account](https://education.github.com/discount_requests/student_application) and GitKraken Pro for
free please see the [tip](https://srse-git-github-zero2hero.netlify.app/setup/github/) about using your academic email address.


If joining an on-line version of the course, we recommend using a two screen set up if possible so you can observe the
live demonstration on one screen and perform the practical exercises on another.

### SCHEDULE

We’ll **kick off at `r params$event_start_time_day1` on `r format(strptime(params$day1, format = "%Y-%m-%d"), "%a %b %d
%Y")`** and aim to have a few breaks throughout the morning, finishing at `r params$event_end_time_day1`. The second
session will follow **at `r params$event_start_time_day2` on `r format(strptime(params$day2, format = "%Y-%m-%d"), "%a %b %d
%Y")`** and follow the same format.

There will be some time at the end of each day for questions and discussions.

### ATTENDANCE

**In the event that you can no longer make it, we please ask that you cancel your ticket so we can offer it to someone on the waiting list**.

### COURSE DELIVERY PLATFORM

We will be using [Blackboard Collaborate](https://www.sheffield.ac.uk/apse/digital/collaborate/students) to deliver the course. On the day please click the link below to join the course room:


## [**JOIN COURSE ROOM**](`r params$session_joining_link`)

For session security, please do not share the joining link.

<br>

See you next week!

Please don’t hesitate to reach out to me with any questions.

<br>

##### `r params$lead_instructor`

**Research Software Engineer**

University of Sheffield
